source 'https://rubygems.org'

gem 'cocoapods', '1.8.4'
gem 'fastlane', '~> 2.137.0'
gem 'danger', '~> 5.13.0'
gem 'danger-lgtm', '~> 1.0.3'
gem 'danger-swiftlint', '~> 0.18.2'
gem 'danger-xcov', '~> 0.4.1'
gem 'danger-xcode_summary', '~> 0.5.0'
gem 'xcpretty-json-formatter', '~> 0.1.1'
